In [1]:
import numpy as np

In [6]:
matrix1 = np.array([[1,4,5,5],[2,5,7,8],[4,5,6,7],[4,9,6,2],[2,4,4,5]])
matrix1

array([[1, 4, 5, 5],
       [2, 5, 7, 8],
       [4, 5, 6, 7],
       [4, 9, 6, 2],
       [2, 4, 4, 5]])

In [7]:
matrix1.shape

(5, 4)

In [10]:
matrix2 = np.reshape(matrix1,[10,2])
matrix2

array([[1, 4],
       [5, 5],
       [2, 5],
       [7, 8],
       [4, 5],
       [6, 7],
       [4, 9],
       [6, 2],
       [2, 4],
       [4, 5]])

In [11]:
matrix2.shape


(10, 2)

#Reshaping it into 3 dimentional array

In [15]:
matrix3 = np.reshape(matrix1, [2,5,2])
matrix3

array([[[1, 4],
        [5, 5],
        [2, 5],
        [7, 8],
        [4, 5]],

       [[6, 7],
        [4, 9],
        [6, 2],
        [2, 4],
        [4, 5]]])

In [16]:
matrix3.shape

(2, 5, 2)

In [17]:
matrix3.T

array([[[1, 6],
        [5, 4],
        [2, 6],
        [7, 2],
        [4, 4]],

       [[4, 7],
        [5, 9],
        [5, 2],
        [8, 4],
        [5, 5]]])

In [18]:
matrix4 = np.array([[1,2,3],[5,3,5],[7,3,2]])
matrix4

array([[1, 2, 3],
       [5, 3, 5],
       [7, 3, 2]])

In [19]:
matrix4.T

array([[1, 5, 7],
       [2, 3, 3],
       [3, 5, 2]])

In [20]:
matrix4

array([[1, 2, 3],
       [5, 3, 5],
       [7, 3, 2]])