In [1]:
import numpy as np

In [3]:
vector1 = np.array([1,3,4,5,5,67,2])
vector1

array([ 1,  3,  4,  5,  5, 67,  2])

In [11]:
matrix1 = np.array([[2,4,5,5],[23,56,67,23],[6,7,8,8]])
matrix1

array([[ 2,  4,  5,  5],
       [23, 56, 67, 23],
       [ 6,  7,  8,  8]])

In [12]:
matrix2 = np.matrix([[2,4,5,5],[23,56,67,23],[6,7,8,8]])
matrix2

matrix([[ 2,  4,  5,  5],
        [23, 56, 67, 23],
        [ 6,  7,  8,  8]])

In [16]:
tensor1 = np.array([[[1,2,3],[5,5,6]],[[7,8,4],[2,5,9]],[[3,5,4],[0,3,4]]])
tensor1

array([[[1, 2, 3],
        [5, 5, 6]],

       [[7, 8, 4],
        [2, 5, 9]],

       [[3, 5, 4],
        [0, 3, 4]]])

In [17]:
vector1.shape

(7,)

In [19]:
matrix1.shape

(3, 4)

In [20]:
tensor1.shape

(3, 2, 3)